[package]
name = "rusted_battle"
version = "0.1.0"
authors = ["Orchaldir <orchaldir@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "dice_probabilities"
path = "src/dice_probabilities.rs"